version: '3.8'

services:
  ollama-proxy:
    build: .
    container_name: ollama_proxy_ui
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped